apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: openvswitch-exec
  namespace: vortex
spec:
  selector:
    matchLabels:
      name: openvswitch-exec
  template:
    metadata:
      labels:
        name: openvswitch-exec
    spec:
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: openvswitch-exec
        image: sdnvortex/openvswitch-exec:latest
        command: ["tail"]
        args: ["-f", "/etc/hostname"]
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /var/run/openvswitch/db.sock
          name: ovs-sock
      volumes:
      - name: ovs-sock #since the UNIX version only add-port, the db.sock is enough
        hostPath:
          path: /run/openvswitch/db.sock
