apiVersion: apps/v1
kind: Deployment
metadata:
  name: vortex-server
  namespace: vortex
  labels:
    app: vortex-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vortex-server
  template:
    metadata:
      labels:
        app: vortex-server
    spec:
      serviceAccountName: vortex-admin
      containers:
      - name: vortex-webapp
        image: sdnvortex/vortex-portal:develop
        ports:
        - containerPort: 8080
      - name: vortex-server
        image: sdnvortex/vortex:v0.1.11
        ports:
        - containerPort: 7890

