# vortex/deploy/helm/apps
apps:
  # vortex/deploy/helm/apps/charts/vortex
  vortex:
    controller:
      replicaCount: 1
      nodeSelector:
        glusterfs: true
    replicaCount: 1
    controller:
      apiserverImageTag: v0.1.15
      webappImageTag: v0.1.12
      portalCPU: 200m
      serverCPU: 100m
    service:
      ports:
        apiserverNodePort: 32326
        webappNodePort: 32767
  # vortex/deploy/helm/apps/charts/network-controller
  network-controller:
    controller:
      imageTag: v0.4.3
      tcpCPU: 100m
      unixCPU: 100m
  # vortex/deploy/helm/apps/charts/prometheus
  prometheus:
    controller:
      replicaCount: 1
      imageTag: v2.2.1
      scrapeInterval: 5s
      retention: 1h
      cpu: 100m
    service:
      nodePort: false
    # vortex/deploy/helm/apps/charts/prometheus/charts/cadvisor
    cadvisor:
      controller:
        imageTag: v0.27.4
        housekeeping_interval: 10s
        cpu: 200m
    # vortex/deploy/helm/apps/charts/prometheus/charts/kube-state-metrics
    kube-state-metrics:
      controller:
        imageTag: v1.3.1
        cpu: 100m
    # vortex/deploy/helm/apps/charts/prometheus/charts/node-exporter
    node-exporter:
      controller:
        imageTag: v1.0.1
        cpu: 100m

# vortex/deploy/helm/services
services:
  # vortex/deploy/helm/services/charts/mongodb
  mongodb:
    controller:
      replicaCount: 1
      cpu: 200m
      image:
        tag: 4.1.1-xenial
      pvc:
        volumeType: nfs
        nfsPath: /nfsshare
        nfsServer: 10.1.14.86
        reclaimPolicy: Recycle
        accessModes: ReadWriteMany
        storageClass: mongo
        storage: 100Gi
    service:
      nodePort: false
